# -*- coding: utf-8 -*-
"""Analysis of Amplitude Envelopes of songs of Kalyaan Thaat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-XIRe_kj19umdekhSq2wVCLoLjtoMfP
"""

!pip install librosa

from IPython.display import Audio
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt

#analyse raga yaman song

yaman_s1="/content/drive/MyDrive/Songs/raga yaman/ye ri ali piya bin.wav"
yaman_s2="/content/drive/MyDrive/Songs/raga yaman/woh sham kuch ajib thi.wav"
yaman_s3="/content/drive/MyDrive/Songs/raga yaman/piya ki nazariyaaa.wav"
yaman_s4="/content/drive/MyDrive/Songs/raga yaman/chandan sa badan.wav"

y0, sr=librosa.load(yaman_s1)
y1, _=librosa.load(yaman_s2)
y2, _=librosa.load(yaman_s3)
y3, _=librosa.load(yaman_s4)

sample_duration_y0=1/sr
duration_of_y0_signal=sample_duration_y0 * len(y0)
print(f" duration of one sample is: {sample_duration_y0 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_y0_signal : .6f} seconds")

sample_duration_y1=1/_
duration_of_y1_signal=sample_duration_y1 * len(y1)
print(f" duration of one sample is: {sample_duration_y1 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_y1_signal : .6f} seconds")

sample_duration_y2=1/_
duration_of_y2_signal=sample_duration_y2 * len(y2)
print(f" duration of one sample is: {sample_duration_y2 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_y2_signal : .6f} seconds")

sample_duration_y3=1/_
duration_of_y3_signal=sample_duration_y3 * len(y3)
print(f" duration of one sample is: {sample_duration_y3 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_y3_signal : .6f} seconds")

plt.figure(figsize=(15, 17))
plt.subplot(5,1,1)
librosa.display.waveplot(y0, alpha=0.5)
plt.title("Waveplot of Raga yaman- ye ri ali piya bin")
plt.ylim(-1,1)
plt.subplot(5,1,2)
librosa.display.waveplot(y1, alpha=0.5)
plt.title("Waveplot of Raga yaman- woh sham kuch ajib thi")
plt.ylim(-1,1)

plt.subplot(5,1,3)
librosa.display.waveplot(y2, alpha=0.5)
plt.title("Waveplot of Raga yaman- piya ki nazariya")
plt.ylim(-1,1)

plt.subplot(5,1,4)
librosa.display.waveplot(y3, alpha=0.5)
plt.title("Waveplot of Raga yaman- chandan sa badan ")
plt.ylim(-1,1)
plt.subplots_adjust(hspace = 0.75)

FRAME_SIZE = 1024
HOP_LENGTH =128
#Calculating the amplitude envelope
def amplitude_envelope(signal, frame_size, hop_length):
  return np.array([max(signal[i:i+frame_size]) for i in range(0, signal.size, hop_length)])
#Amplitude Envelope for individual genre
ae_y0 = amplitude_envelope(y0, FRAME_SIZE, HOP_LENGTH)
ae_y1 = amplitude_envelope(y1, FRAME_SIZE, HOP_LENGTH)
ae_y2 = amplitude_envelope(y2, FRAME_SIZE, HOP_LENGTH)
ae_y3 = amplitude_envelope(y3, FRAME_SIZE, HOP_LENGTH)

frames = range(0, ae_y0.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,1)
librosa.display.waveplot(ae_y0, alpha=0.5)
plt.plot(t, ae_y0, color="r")
plt.title("Amplitude Envelope of raga yaman- ye ri ali piya bin")
plt.ylim(-1,1)

frames = range(0, ae_y1.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,2)
librosa.display.waveplot(ae_y1, alpha=0.5)
plt.plot(t, ae_y1, color="r")
plt.title("Amplitude Envelope of raga yaman- woh sham bhi kuch ajib thi")
plt.ylim(-1,1)

frames = range(0, ae_y2.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,3)
librosa.display.waveplot(ae_y2, alpha=0.5)
plt.plot(t, ae_y2, color="r")
plt.title("Amplitude Envelope of raga yaman- piya ki nazariya")
plt.ylim(-1,1)

frames = range(0, ae_y3.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,4)
librosa.display.waveplot(ae_y3, alpha=0.5)
plt.plot(t, ae_y3, color="r")
plt.title("Amplitude Envelope of raga yaman- chandan sa badan")
plt.ylim(-1,1)

plt.subplots_adjust(hspace = 0.75)

#analyse raga bhupali song

bhupali_s1="/content/drive/MyDrive/Songs/raga bhupali/naman kar chatur shri guru charan.wav"
bhupali_s2="/content/drive/MyDrive/Songs/raga bhupali/main jahan rahu.wav"
bhupali_s3="/content/drive/MyDrive/Songs/raga bhupali/jaun tode charan.wav"
bhupali_s4="/content/drive/MyDrive/Songs/raga bhupali/dekha ek khawab.wav"

b0, sr=librosa.load(bhupali_s1)
b1, _=librosa.load(bhupali_s2)
b2, _=librosa.load(bhupali_s3)
b3, _=librosa.load(bhupali_s4)

sample_duration_b0=1/sr
duration_of_b0_signal=sample_duration_b0 * len(b0)
print(f" duration of one sample is: {sample_duration_b0 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_b0_signal : .6f} seconds")

sample_duration_b1=1/_
duration_of_b1_signal=sample_duration_b1 * len(b1)
print(f" duration of one sample is: {sample_duration_b1 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_b1_signal : .6f} seconds")

sample_duration_b2=1/_
duration_of_b2_signal=sample_duration_b2 * len(b2)
print(f" duration of one sample is: {sample_duration_b2 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_b2_signal : .6f} seconds")

sample_duration_b3=1/_
duration_of_b3_signal=sample_duration_b3 * len(b3)
print(f" duration of one sample is: {sample_duration_b3 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_b3_signal : .6f} seconds")

plt.figure(figsize=(15, 17))
plt.subplot(5,1,1)
librosa.display.waveplot(b0, alpha=0.5)
plt.title("Waveplot of Raga bhupali- naman kar chatur shri guru charan")
plt.ylim(-1,1)
plt.subplot(5,1,2)
librosa.display.waveplot(b1, alpha=0.5)
plt.title("Waveplot of Raga bhupali- main jahan rahu")
plt.ylim(-1,1)

plt.subplot(5,1,3)
librosa.display.waveplot(b2, alpha=0.5)
plt.title("Waveplot of Raga bhupali- jaun tode charan")
plt.ylim(-1,1)

plt.subplot(5,1,4)
librosa.display.waveplot(b3, alpha=0.5)
plt.title("Waveplot of Raga bhupali- dekha ek khawab")
plt.ylim(-1,1)
plt.subplots_adjust(hspace = 0.75)

FRAME_SIZE = 1024
HOP_LENGTH =128
#Calculating the amplitude envelope
def amplitude_envelope(signal, frame_size, hop_length):
  return np.array([max(signal[i:i+frame_size]) for i in range(0, signal.size, hop_length)])
#Amplitude Envelope for individual genre
ae_b0 = amplitude_envelope(b0, FRAME_SIZE, HOP_LENGTH)
ae_b1 = amplitude_envelope(b1, FRAME_SIZE, HOP_LENGTH)
ae_b2 = amplitude_envelope(b2, FRAME_SIZE, HOP_LENGTH)
ae_b3 = amplitude_envelope(b3, FRAME_SIZE, HOP_LENGTH)

frames = range(0, ae_b0.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,1)
librosa.display.waveplot(ae_b0, alpha=0.5)
plt.plot(t, ae_b0, color="r")
plt.title("Amplitude Envelope of raga bhupali- naman kar chatur shri gurucharan")
plt.ylim(-1,1)

frames = range(0, ae_b1.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,2)
librosa.display.waveplot(ae_b1, alpha=0.5)
plt.plot(t, ae_b1, color="r")
plt.title("Amplitude Envelope of raga bhupali- main jahan rahu")
plt.ylim(-1,1)

frames = range(0, ae_b2.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,3)
librosa.display.waveplot(ae_b2, alpha=0.5)
plt.plot(t, ae_b2, color="r")
plt.title("Amplitude Envelope of raga bhupali- jaun tode charan")
plt.ylim(-1,1)

frames = range(0, ae_b3.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,4)
librosa.display.waveplot(ae_y3, alpha=0.5)
plt.plot(t, ae_b3, color="r")
plt.title("Amplitude Envelope of raga bhupali- dekha ek khawab ")
plt.ylim(-1,1)

plt.subplots_adjust(hspace = 0.75)

#analyse raga kedar songs

kedar_s1="/content/drive/MyDrive/Songs/raga kedar/soch samaj man meet piyarava.wav"
kedar_s2="/content/drive/MyDrive/Songs/raga kedar/kanha re.wav"
kedar_s3="/content/drive/MyDrive/Songs/raga kedar/humko mann ki shakti dena.wav"
kedar_s4="/content/drive/MyDrive/Songs/raga kedar/darshan do ghanshyam nath mori.wav"

k0, sr=librosa.load(kedar_s1)
k1, _=librosa.load(kedar_s2)
k2, _=librosa.load(kedar_s3)
k3, _=librosa.load(kedar_s4)

sample_duration_k0=1/sr
duration_of_k0_signal=sample_duration_k0 * len(k0)
print(f" duration of one sample is: {sample_duration_k0 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_k0_signal : .6f} seconds")

sample_duration_k1=1/_
duration_of_k1_signal=sample_duration_k1 * len(k1)
print(f" duration of one sample is: {sample_duration_k1 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_k1_signal : .6f} seconds")

sample_duration_k2=1/_
duration_of_k2_signal=sample_duration_k2 * len(k2)
print(f" duration of one sample is: {sample_duration_k2 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_k2_signal : .6f} seconds")

sample_duration_k3=1/_
duration_of_k3_signal=sample_duration_k3 * len(k3)
print(f" duration of one sample is: {sample_duration_k3 : .6f} seconds")
print(f"duration of the audio signal is: {duration_of_k3_signal : .6f} seconds")

plt.figure(figsize=(15, 17))
plt.subplot(5,1,1)
librosa.display.waveplot(k0, alpha=0.5)
plt.title("Waveplot of Raga kedar- soch samaj mann meet piyarwa")
plt.ylim(-1,1)
plt.subplot(5,1,2)
librosa.display.waveplot(k1, alpha=0.5)
plt.title("Waveplot of Raga kedar- kanha re")
plt.ylim(-1,1)

plt.subplot(5,1,3)
librosa.display.waveplot(k2, alpha=0.5)
plt.title("Waveplot of Raga kedar- humko mann ki shakti dena")
plt.ylim(-1,1)

plt.subplot(5,1,4)
librosa.display.waveplot(k3, alpha=0.5)
plt.title("Waveplot of Raga kedar- darshan do ghanshyam nath mori")
plt.ylim(-1,1)
plt.subplots_adjust(hspace = 0.75)

FRAME_SIZE = 1024
HOP_LENGTH =128
#Calculating the amplitude envelope
def amplitude_envelope(signal, frame_size, hop_length):
  return np.array([max(signal[i:i+frame_size]) for i in range(0, signal.size, hop_length)])
#Amplitude Envelope for individual genre
ae_k0 = amplitude_envelope(k0, FRAME_SIZE, HOP_LENGTH)
ae_k1 = amplitude_envelope(k1, FRAME_SIZE, HOP_LENGTH)
ae_k2 = amplitude_envelope(k2, FRAME_SIZE, HOP_LENGTH)
ae_k3 = amplitude_envelope(k3, FRAME_SIZE, HOP_LENGTH)

frames = range(0, ae_k0.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,1)
librosa.display.waveplot(ae_k0, alpha=0.5)
plt.plot(t, ae_k0, color="r")
plt.title("Amplitude Envelope of Raga kedar- soch samaj mann meet piyarwa")
plt.ylim(-1,1)

frames = range(0, ae_k1.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,2)
librosa.display.waveplot(ae_k1, alpha=0.5)
plt.plot(t, ae_k1, color="r")
plt.title("Amplitude Envelope of Raga kedar- kanha re")
plt.ylim(-1,1)

frames = range(0, ae_k2.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,3)
librosa.display.waveplot(ae_k2, alpha=0.5)
plt.plot(t, ae_k2, color="r")
plt.title("Amplitude Envelope of Raga kedar- humko mann ki shakti dena")
plt.ylim(-1,1)

frames = range(0, ae_k3.size)
t = librosa.frames_to_time(frames, hop_length=HOP_LENGTH)
plt.figure(figsize=(15, 17))
plt.subplot(5,1,4)
librosa.display.waveplot(ae_k3, alpha=0.5)
plt.plot(t, ae_k3, color="r")
plt.title("Amplitude Envelope of Raga kedar- darshan do ghanshyam nath mori")
plt.ylim(-1,1)

plt.subplots_adjust(hspace = 0.75)

